# Generated by Django 3.2.6 on 2021-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='abilities',
            field=models.CharField(choices=[], default='ability', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='dexid',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='type1',
            field=models.CharField(default='type1', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='type2',
            field=models.CharField(default='type2', max_length=12),
            preserve_default=False,
        ),
    ]
