# Generated by Django 3.2.6 on 2021-08-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20210812_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='poke_name',
        ),
    ]
