# Generated by Django 3.2.6 on 2021-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_auto_20210819_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ability1',
            field=models.CharField(blank=True, default='ability ?', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='ability2',
            field=models.CharField(blank=True, default='ability ?', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='hidden_ability',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type1',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type2',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
