# Generated by Django 3.2.6 on 2021-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_auto_20210819_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='evolves_from_species',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
