# Generated by Django 3.2.6 on 2021-08-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_card_evolves_from_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='gender_rate',
            field=models.SmallIntegerField(default=4),
        ),
    ]
