# Generated by Django 3.2.6 on 2021-08-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_card_gender_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.AlterField(
            model_name='card',
            name='dexid',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
