# Generated by Django 3.2.6 on 2021-09-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_auto_20210906_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='beastball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='cherishball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='diveball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='dreamball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='duskball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='fastball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='friendball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='greatball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='healball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='heavyball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='levelball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='loveball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='lureball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='luxuryball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='masterball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='moonball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='nestball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='netball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='pokeball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='premierball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='quickball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='repeatball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='safariball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='sportball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='timerball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='ultraball_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='poke_sprite',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='shiny_sprite',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
