# Generated by Django 3.2.6 on 2021-10-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_auto_20210930_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='DEFAULT', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='DEFAULT', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='hp_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='DEFAULT', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='sp_attack_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='DEFAULT', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='sp_defense_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='DEFAULT', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='speed_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='DEFAULT', max_length=12),
        ),
    ]
