# Generated by Django 3.2.6 on 2021-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_auto_20211004_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ability',
            field=models.CharField(blank=True, default='ability', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nature',
            field=models.CharField(choices=[('DEFAULT', '-'), ('HARDY', 'Hardy'), ('LONELY', 'Lonely'), ('BRAVE', 'Brave'), ('ADAMANT', 'Adamant'), ('NAUGHTY', 'Naughty'), ('BOLD', 'Bold'), ('DOCILE', 'Docile'), ('RELAXED', 'Relaxed'), ('IMPISH', 'Impish'), ('LAX', 'Lax'), ('TIMID', 'Timid'), ('HASTY', 'Hasty'), ('SERIOUS', 'Serious'), ('JOLLY', 'Jolly'), ('NAIVE', 'Naive'), ('MODEST', 'Modest'), ('MILD', 'Mild'), ('QUIET', 'Quiet'), ('BASHFUL', 'Bashful'), ('RASH', 'Rash'), ('CALM', 'Calm'), ('GENTLE', 'Gentle'), ('SASSY', 'Sassy'), ('CAREFUL', 'Careful'), ('QUIRKY', 'Quirky')], default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='attack_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='hp_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='sp_attack_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='sp_defense_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='speed_iv',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
    ]
