# Generated by Django 3.2.6 on 2021-10-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_auto_20211004_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ability_shiny',
            field=models.CharField(blank=True, default='ability', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='attack_iv_shiny',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='beastball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='cherishball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='defense_iv_shiny',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='diveball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='dreamball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='duskball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='fastball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='friendball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='greatball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='healball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='heavyball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='hp_iv_shiny',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='levelball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='loveball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='lureball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='luxuryball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='masterball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='moonball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='nature_shiny',
            field=models.CharField(choices=[('DEFAULT', '-'), ('HARDY', 'Hardy'), ('LONELY', 'Lonely'), ('BRAVE', 'Brave'), ('ADAMANT', 'Adamant'), ('NAUGHTY', 'Naughty'), ('BOLD', 'Bold'), ('DOCILE', 'Docile'), ('RELAXED', 'Relaxed'), ('IMPISH', 'Impish'), ('LAX', 'Lax'), ('TIMID', 'Timid'), ('HASTY', 'Hasty'), ('SERIOUS', 'Serious'), ('JOLLY', 'Jolly'), ('NAIVE', 'Naive'), ('MODEST', 'Modest'), ('MILD', 'Mild'), ('QUIET', 'Quiet'), ('BASHFUL', 'Bashful'), ('RASH', 'Rash'), ('CALM', 'Calm'), ('GENTLE', 'Gentle'), ('SASSY', 'Sassy'), ('CAREFUL', 'Careful'), ('QUIRKY', 'Quirky')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='nestball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='netball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='pokeball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='premierball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='quickball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='repeatball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='safariball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='sp_attack_iv_shiny',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='sp_defense_iv_shiny',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='speed_iv_shiny',
            field=models.CharField(choices=[('DEFAULT', '-'), ('NO_GOOD', 'No Good'), ('DECENT', 'Decent'), ('PRETTY_GOOD', 'Pretty Good'), ('VERY_GOOD', 'Very Good'), ('FANTASTIC', 'Fantastic'), ('BEST', 'Best')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='sportball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='timerball_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='ultraball_shiny',
            field=models.BooleanField(default=False),
        ),
    ]
